name: ci-pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install poetry==1.6.1
        poetry install
        
    - name: Linting
      run: |
          poetry run ruff check
          poetry run ruff format
          poetry run mypy .

    - name: Unit tests
      run: |
          poetry run pytest
          